language: python

python:
  - "2.7"

#addons:
#  postgresql: "9.1"

branches:
  only:
    - master
    - develop
    - travis

-before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y # For postgresql-9.1-postgis-2.1

install:
  - sudo apt-get -qq -y update
  - sudo apt-get -y install postgresql-9.6-postgis-2.3 osm2pgsql

before_script:
  - echo "Build starting on " `date`
  - psql -U postgres -c "create extension postgis"
  - sudo pip install requirements-dev.txt

script:
  - PYTHONPATH=`pwd`/reporter:`pwd`:$(PYTHONPATH) nosetests -v --with-id \
    --with-xcoverage --with-xunit --verbose --cover-package=reporter reporter

notifications:
  irc:
    channels:
      - "irc.freenode.org#kartoza"
    use_notice: true

  email:
    - tim@kartoza.com
